name: mira scraper

on:
  push:
    branch:
      master
  #schedule:
  #  - cron: '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Brussels"
      - uses: actions/checkout@v3
      - name: fetch an image
        run: |-
          ./mira.sh
      - name: Commit and push if dashboard.txt changed
        run: |-
          git config user.name "Automated"
          git config user.email "github-actions@users.noreply.github.com"
          git add west.jpg
          timestamp=$(date)
          git commit -m "Latest image: ${timestamp}" || exit 0
          git push
