name: mira scraper

on:
  push:
    branch:
      master
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    concurrency:
        group: mira-unique-run
        cancel-in-progress: true

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Brussels"
      - uses: actions/checkout@v3
      - name: make sure our working copy is up to date
        run: |-
          git pull
      - name: Install ghostscript for imagemagick
        run: sudo apt-get install ghostscript
      - name: fetch an image
        run: |-
          ./mira.sh
      - name: Commit and push the new picture
        run: |-
          git config user.name "Automated"
          git config user.email "github-actions@users.noreply.github.com"
          timestamp=$(date)
          git commit -m "Latest image: ${timestamp}" || exit 0
          git push
