name: mira scraper

on:
  #push:
  #  branch:
  #    master
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Brussels"
      - uses: actions/checkout@v3
      - name: make sure our working copy is up to date
        run: |-
          git pull
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: python -m pip install --upgrade pip bs4 pandas pytz
      - name: Run Scraper
        run: |-
          python fetch_prices/process_purchases.py | tee dashboard.txt;
          # if process_purchases.py does not finish correctly we revert dashboard.txt
          if [ ${PIPESTATUS[0]} -ne 0 ]; then git checkout dashboard.txt; fi
      - name: Commit and push if dashboard.txt changed
        run: |-
          git config user.name "Automated"
          git config user.email "github-actions@users.noreply.github.com"
          git add dashboard.txt
          timestamp=$(date)
          git commit -m "Latest prices: ${timestamp}" || exit 0
          git push
